name: Deploy via SFTP to IONOS

on:
  push:
    branches:
      - main

jobs:
  sftp-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Remove git folders before upload
        run: rm -rf .git .github

      - name: Upload files to IONOS via SFTP
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          server: ${{ secrets.SFTP_HOST }}
          username: ${{ secrets.SFTP_USERNAME }}
          password: ${{ secrets.SFTP_PASSWORD }}
          port: 22
          local_path: ./
          remote_path: '/swapp/'
          sftp_only: true
          exclude: '[".git", ".github", "node_modules"]'
